drop table if exists spittle;
drop table if exists spitter;
create table spittle (
	id int generated by default as identity (start with 1) primary key,
	message varchar(140) not null,
	created_at timestamp not null,
	latitude double,
	longitude double
);

create table spitter (
	id int generated by default as identity (start with 1) primary key,
	username varchar(20) unique not null,
	password varchar(20) not null,
	first_name varchar(30) not null,
	last_name varchar(30) not null,
	email varchar(30)
);